on: [push]

jobs:
  my-job:
    run-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: run the action
        id: hello
        uses: ./
        with:
          myInput: 'Nisarg'
      - name: output
        run: |
           echo ${{ steps.hello.output.memory }}
           echo "total memory successfully output"
